"""empty message

Revision ID: 406a800357c8
Revises: d9e1d7e3a80f
Create Date: 2016-02-02 20:59:40.684257

"""

# revision identifiers, used by Alembic.
revision = '406a800357c8'
down_revision = 'd9e1d7e3a80f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_maintenance', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_maintenance')
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###
