"""empty message

Revision ID: d9e1d7e3a80f
Revises: 86ebe1c93d99
Create Date: 2016-02-02 17:01:54.314093

"""

# revision identifiers, used by Alembic.
revision = 'd9e1d7e3a80f'
down_revision = '86ebe1c93d99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(length=9), nullable=True))
    op.add_column('users', sa.Column('phonenumber_locale', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.drop_column('users', 'phonenumber_locale')
    op.drop_column('users', 'phonenumber')
    ### end Alembic commands ###
